// <auto-generated />
using System;
using Gestion.Api.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111185918_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion.Api.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEntidad")
                        .HasColumnType("int");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("Id");

                    b.HasIndex("IdEntidad");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.CategoriaAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("bit");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("IdTipoDato")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdTipoDato");

                    b.ToTable("CategoriaAtributo", (string)null);
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Entidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Entidad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGuid = new Guid("ed97a159-d788-4f4b-b049-4704ef3e1653"),
                            Nombre = "Somos Habitos"
                        });
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.ProductoAtributoValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCategoriaAtributo")
                        .HasColumnType("int");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaAtributo");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductoAtributoValor", (string)null);
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Revocado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.TipoDato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("TipoDato", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGuid = new Guid("bc9c1b1a-4e45-4aa8-b64c-72624a0a2fff"),
                            Tipo = "Entero"
                        },
                        new
                        {
                            Id = 2,
                            IdGuid = new Guid("fdafbd38-c57a-4593-955a-ddc232c3f209"),
                            Tipo = "Decimal"
                        },
                        new
                        {
                            Id = 3,
                            IdGuid = new Guid("ac1515ab-7562-4fc7-a436-ef17586e07d6"),
                            Tipo = "Texto"
                        },
                        new
                        {
                            Id = 4,
                            IdGuid = new Guid("566b3b56-b0b3-422a-92c2-e442d70c95d5"),
                            Tipo = "Tabla"
                        },
                        new
                        {
                            Id = 5,
                            IdGuid = new Guid("1263f9d7-7bdf-43fa-910b-1dbbe01a5b67"),
                            Tipo = "Booleano"
                        },
                        new
                        {
                            Id = 6,
                            IdGuid = new Guid("6ec97364-4df9-4f2f-896c-dc995c52b1ee"),
                            Tipo = "Fecha"
                        });
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Aministrador",
                            IdGuid = new Guid("31c76205-6ddd-43a6-8bc4-0c748ddfcffa")
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Empleado",
                            IdGuid = new Guid("c1a321cc-7a0a-4079-a6d2-d17f9f045fd3")
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Usuario",
                            IdGuid = new Guid("ad9b7732-2a84-4c78-9a47-717d5b47eef0")
                        });
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdEntidad")
                        .HasColumnType("int");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdEntidad");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Categoria", b =>
                {
                    b.HasOne("Gestion.Api.Models.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("IdEntidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Categoria_Entidad_IdEntidad");

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.CategoriaAtributo", b =>
                {
                    b.HasOne("Gestion.Api.Models.Entities.Categoria", "Categoria")
                        .WithMany("Atributos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaAtributo_Categoria_IdCategoria");

                    b.HasOne("Gestion.Api.Models.Entities.TipoDato", "TipoDato")
                        .WithMany()
                        .HasForeignKey("IdTipoDato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaAtributo_TipoDato_IdTipoDato");

                    b.Navigation("Categoria");

                    b.Navigation("TipoDato");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Producto", b =>
                {
                    b.HasOne("Gestion.Api.Models.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Categoria_IdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.ProductoAtributoValor", b =>
                {
                    b.HasOne("Gestion.Api.Models.Entities.CategoriaAtributo", "CategoriaAtributo")
                        .WithMany()
                        .HasForeignKey("IdCategoriaAtributo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductoAtributoValor_CategoriaAtributo_IdCategoriaAtributo");

                    b.HasOne("Gestion.Api.Models.Entities.Producto", "Producto")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaAtributo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("Gestion.Api.Models.Entities.Usuario", "Usuario")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Gestion.Api.Models.Entities.RefreshToken", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Usuario", b =>
                {
                    b.HasOne("Gestion.Api.Models.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("IdEntidad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gestion.Api.Models.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entidad");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Categoria", b =>
                {
                    b.Navigation("Atributos");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Producto", b =>
                {
                    b.Navigation("Propiedades");
                });

            modelBuilder.Entity("Gestion.Api.Models.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
